spring.application.name=backend

spring.datasource.url=jdbc:postgresql://aws-0-ap-northeast-1.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.rqvfsgozijbjrjirgwxh
spring.datasource.password=Farm_verse4

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=8f4c2b9d7e1a5f6c3d8b1a9e7f4d2c6b5a8e1f9d3c7b6a2e5f8d1c4b7a9e6f2
jwt.expiration=86400000
